(* generated by dune *)

(** @canonical Memtrace.Backtrace_codec *)
module Backtrace_codec = Memtrace__Backtrace_codec

(** @canonical Memtrace.Buf *)
module Buf = Memtrace__Buf

(** @canonical Memtrace.Geometric_sampler *)
module Geometric_sampler = Memtrace__Geometric_sampler

(** @canonical Memtrace.Location_codec *)
module Location_codec = Memtrace__Location_codec

(** @canonical Memtrace.Memprof_tracer *)
module Memprof_tracer = Memtrace__Memprof_tracer

(** @canonical Memtrace.Trace *)
module Trace = Memtrace__Trace
