(* generated by dune *)

(** @canonical Stdint.Bytes_conv *)
module Bytes_conv = Stdint__Bytes_conv

(** @canonical Stdint.Infix *)
module Infix = Stdint__Infix

(** @canonical Stdint.Int_wrapper *)
module Int_wrapper = Stdint__Int_wrapper

(** @canonical Stdint.Stdint_stdlib_ *)
module Stdint_stdlib_ = Stdint__Stdint_stdlib_

(** @canonical Stdint.Str_conv *)
module Str_conv = Stdint__Str_conv
