(* generated by dune *)

(** @canonical Sedlex_ppx.Iso *)
module Iso = Sedlex_ppx__Iso

(** @canonical Sedlex_ppx.Ppx_sedlex *)
module Ppx_sedlex = Sedlex_ppx__Ppx_sedlex

(** @canonical Sedlex_ppx.Sedlex *)
module Sedlex = Sedlex_ppx__Sedlex

(** @canonical Sedlex_ppx.Sedlex_cset *)
module Sedlex_cset = Sedlex_ppx__Sedlex_cset

(** @canonical Sedlex_ppx.Unicode *)
module Unicode = Sedlex_ppx__Unicode

(** @canonical Sedlex_ppx.Xml *)
module Xml = Sedlex_ppx__Xml
