name: Make .smt2 files
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  generate_smt2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      # Dafny likes `4.12.1`, FStar likes `4.13.3`, Viper likes `4.8.7`
      - name: Install Z3 for newer version
        uses: pavpanchekha/setup-z3@v1.3
        with:
          version: 4.12.1
          distribution: 'glibc-2.35'

      # Viper
      - uses: sbt/setup-sbt@v1

      # Dafny
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Dafny & Carbon
      - name: Install Boogie
        run: dotnet tool install --global boogie

      # FStar
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      # - name: Debugging with tmate
      #   uses: mxschmitt/action-tmate@v3.19

      - name: Make smt2 files
        run: ./make_smt2.sh

      - name: Merge in from main
        run: |
          git config --global user.email "gh-action[bot]@users.noreply.github.com"
          git config --global user.name "gh-action[bot]"
          git add -A
          git stash
          git fetch origin smt2
          git checkout FETCH_HEAD -b smt2
          git merge -X theirs main
          git checkout main
          git stash show && git stash pop || true

      - name: Commit changes
        run: |
          git symbolic-ref HEAD refs/heads/smt2
          git add -A
          git diff-index --quiet HEAD || git commit -m "Rebuild \".smt2\" files with new main"
          git push -u origin smt2
